INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10001,  'Ross', 'Hyderabad', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10002,  'Rachel', 'New York', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10003,  'Pheobe', 'Amsterdam', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10004,  'Chandler', 'London', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10005,  'Joey', 'Rome', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE ) 
VALUES(10006,  'Monica', 'Cairo', CURRENT_TIMESTAMP());